### ISSUE TITLE
Input Handling 

### ISSUE THREAD

**Issue by ConnorCotturone** [ConnorCotturone/senior-game-engine#2]
Add input handling class

**Comment by jtcurlin** [comment]
Done. 


**Files** 

[input_types.h](https://github.com/ConnorCotturone/senior-game-engine/blob/e7e6cb1f32aa37195f0536ea694af4d9f486b316/include/input/input_types.h)

[input_manager.h](https://github.com/ConnorCotturone/senior-game-engine/blob/e7e6cb1f32aa37195f0536ea694af4d9f486b316/include/input/input_manager.h)
[input_manager.cpp](https://github.com/ConnorCotturone/senior-game-engine/blob/e7e6cb1f32aa37195f0536ea694af4d9f486b316/src/input/input_manager.cpp)

[window_manager.h](https://github.com/ConnorCotturone/senior-game-engine/blob/e7e6cb1f32aa37195f0536ea694af4d9f486b316/include/core/window_manager.h)
[window_manager.cpp](https://github.com/ConnorCotturone/senior-game-engine/blob/e7e6cb1f32aa37195f0536ea694af4d9f486b316/src/core/window_manager.cpp)

[engine_events.h](https://github.com/ConnorCotturone/senior-game-engine/blob/e7e6cb1f32aa37195f0536ea694af4d9f486b316/include/ecs/events/engine_events.h)

**Commits** 

6ff7981218e64d59fb6a2c67df68616976340ecd 
f0716fc95ecfb83bf6371f17067202f5bb8ab38f.
