### ISSUE TITLE
Event Handler

### ISSUE THREAD

**Issue by ConnorCotturone** [ConnorCotturone/senior-game-engine#4]

**Comment by jtcurlin** [comment]
done.

**Commits**

6ff7981218e64d59fb6a2c67df68616976340ecd

**Files**

[event.h](https://github.com/ConnorCotturone/senior-game-engine/blob/e7e6cb1f32aa37195f0536ea694af4d9f486b316/include/ecs/event.h)

[event_manager.h](https://github.com/ConnorCotturone/senior-game-engine/blob/e7e6cb1f32aa37195f0536ea694af4d9f486b316/include/ecs/event_manager.h)
[event_manager.cpp](https://github.com/ConnorCotturone/senior-game-engine/blob/e7e6cb1f32aa37195f0536ea694af4d9f486b316/src/ecs/event_manager.cpp)

[engine_events.h](https://github.com/ConnorCotturone/senior-game-engine/blob/e7e6cb1f32aa37195f0536ea694af4d9f486b316/include/ecs/events/engine_events.h)
